@startuml
title Initialization
box "service process" #LightBlue
participant ConcreteImpl #Wheat
participant DBusAdapter #PaleGreen
end box

ConcreteImpl -[hidden]> DBusAdapter
DBusAdapter -> DBusAdapter: Init(ConcreteImpl) 
DBusAdapter -> DBus: Export 

box "client process" #Lavender
participant DBusProxy #PaleGreen
end box

DBusProxy -> DBusProxy: Init 
DBusProxy -> DBus: ConnectToRemoteObject
note right: Tries to fetch all properties \n including "ready" property 
DBusProxy -> DBus: GetAllProperties
DBus -> DBusAdapter: GetAllProperties
DBusAdapter --> DBus: return properties
DBus --> DBusProxy: return properties
@enduml