@startuml
title DBus Property 
box "service process" #LightBlue
participant ConcreteImpl #Wheat
participant DBusAdapter #PaleGreen
end box

DBusAdapter -[hidden]> DBus: Set<Property>

box "client process" #Lavender
participant DBusProxy #PaleGreen
end box

DBusProxy -> DBus: Set<Property>

DBusAdapter <- DBus: Set<Property>
alt Set<Property>Callback exists
DBusAdapter ->  ConcreteImpl: Set<Property>Callback
end
alt Set<Property>Callback does not exists \n or returns nil error
DBusAdapter -> DBus: PropertiesChanged
DBus -> DBusProxy: PropertiesChanged 
DBusProxy -> DBusProxy: Update<Property>
else value invalid
DBusAdapter --> DBus: Return DBus error
DBus --> DBusProxy: Return DBus error
end
@enduml