name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean 

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15.3

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
          
    - name: Install dbus
      run: |
        sudo apt update
        sudo apt install dbus dbus-x11 -y

    - name: Install python3
      run: sudo apt install python3 python3-setuptools python3-pip -y

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

    - name: Generate
      run: go generate -v ./...
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
